language: python

python:
  - "2.7"
  - "3.5"
  - "3.7"

git:
  depth: false

branches:
  only:
    - master

install:
  - pip install pyyaml pylint yapf

script:
  - sh -c "pylint *.py"
  - sh -c "yapf --style=google -d *.py"
